# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('introduction', models.TextField(max_length=200)),
                ('pre_app', models.TextField(max_length=50)),
                ('post_app', models.TextField(max_length=50)),
                ('uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('jobs', models.ManyToManyField(to='major.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('cpu_number', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('os', models.CharField(max_length=30)),
                ('uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NodeAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Applications')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.JobStream')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('process', models.CharField(max_length=10)),
                ('nodes', models.ManyToManyField(to='major.EnvironmentJob')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('parameter', models.ManyToManyField(to='major.Parameters')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('real_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=200)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.TaskType'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Users'),
        ),
        migrations.AddField(
            model_name='parameterconfigs',
            name='parameter',
            field=models.ManyToManyField(to='major.Parameters'),
        ),
        migrations.AddField(
            model_name='parameterconfigs',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Tasks'),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.NodeType'),
        ),
        migrations.AddField(
            model_name='environmentjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.JobStream'),
        ),
        migrations.AddField(
            model_name='environment',
            name='node',
            field=models.ManyToManyField(to='major.Node'),
        ),
    ]
