# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentjob',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='environmentjob',
            name='job',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='nodes',
            field=models.ManyToManyField(to='major.NodeJob'),
        ),
        migrations.DeleteModel(
            name='EnvironmentJob',
        ),
    ]
