# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0003_environmentjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='nodes',
            field=models.ManyToManyField(to='major.EnvironmentJob'),
        ),
    ]
