# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0004_auto_20160713_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='nodes',
            field=models.ManyToManyField(to='major.NodeJob'),
        ),
    ]
