# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0006_auto_20160713_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterconfigs',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='parameterconfigs',
            name='task_id',
        ),
        migrations.AddField(
            model_name='parameters',
            name='collect_name',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParameterConfigs',
        ),
    ]
