# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0007_auto_20160721_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='major.Parameters')),
            ],
        ),
    ]
