# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0008_parameterconfigs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Environment')),
                ('node', models.ManyToManyField(to='major.Node')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='parameterconfigs',
            field=models.ManyToManyField(to='major.ParameterConfigs'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='simulationEnvironments',
            field=models.ManyToManyField(to='major.SimulationEnvironment'),
        ),
    ]
