# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0009_auto_20160727_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 27, 6, 37, 20, 13000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 27, 6, 37, 25, 537000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
