# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0010_auto_20160727_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_density_score', models.IntegerField(blank=True, null=True)),
                ('sorted_consume_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobAbnormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=256)),
                ('parameter', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField()),
                ('schedule_num', models.IntegerField()),
                ('job_type', models.IntegerField()),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Benchmark')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_all_cpi', models.FloatField()),
                ('cpu_all_idle', models.FloatField()),
                ('cpu_all_sywa', models.FloatField()),
                ('mem_all_mem_ratio', models.FloatField()),
                ('mem_all_swap_ratio', models.FloatField()),
                ('disk_all_write', models.FloatField()),
                ('disk_all_read', models.FloatField()),
                ('net_all_recv', models.FloatField()),
                ('net_all_send', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average_score', to='major.ParameterScore')),
                ('curve_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curve_score', to='major.ParameterScore')),
                ('max_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_score', to='major.ParameterScore')),
                ('min_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_score', to='major.ParameterScore')),
            ],
        ),
        migrations.AddField(
            model_name='jobstream',
            name='job_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='data_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='p_tag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='run_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='main_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.ParameterScore'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.StatisticInfo'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='benchmark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='major.Benchmark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='main_feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='major.ParameterScore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='statistic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='major.StatisticInfo'),
            preserve_default=False,
        ),
    ]
