# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0023_tasks_speedconfigure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compute', models.FloatField()),
                ('flops', models.FloatField()),
                ('IO', models.FloatField()),
                ('mem', models.FloatField()),
                ('net', models.FloatField()),
            ],
        ),
    ]
