# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0025_tasks_speedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('performance_up', models.IntegerField()),
                ('time_up', models.IntegerField()),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.SpeedConfigure')),
            ],
        ),
    ]
