# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0026_speedtrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='SpeedTrend',
            field=models.ManyToManyField(to='major.SpeedTrend'),
        ),
    ]
