# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0027_tasks_speedtrend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterscore',
            name='cpu_all_cpi',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
