# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0040_remove_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpConfigT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField()),
                ('jobname', models.CharField(max_length=20)),
                ('nodename', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
