# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0044_jobabnormal_jobname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
