# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0045_abnormaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormaltype',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
