# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0046_auto_20160907_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='job_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
