# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0047_jobinfo_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormaltype',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_number',
            field=models.CharField(max_length=255),
        ),
    ]
