# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0049_auto_20160913_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpconfigt',
            name='jobname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cmpconfigt',
            name='nodename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cmpconfigt',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
