# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0050_auto_20160918_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='regression_end_time',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='tasks',
            name='regression_start_time',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
