# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0051_auto_20160920_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='regression_jobstream',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='major.JobStream'),
        ),
    ]
