# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0055_auto_20160922_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proID', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=513)),
            ],
        ),
        migrations.CreateModel(
            name='RunModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='displaymodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.RunModule'),
        ),
    ]
