# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0058_auto_20161009_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='displaymodule',
        ),
        migrations.AddField(
            model_name='job',
            name='runmodule',
            field=models.ManyToManyField(to='major.RunModule'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
