# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0060_jobinfo_runmodule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunModule',
            new_name='RunMode',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='runmodule',
            new_name='runmode',
        ),
        migrations.RenameField(
            model_name='jobinfo',
            old_name='runmodule',
            new_name='runmode',
        ),
    ]
