# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0061_auto_20161009_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runmode',
            old_name='modulename',
            new_name='name',
        ),
    ]
