# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0065_auto_20161020_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='data_id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='data_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
